_BASE_: "../Base-TESTR.yaml"
DATASETS:
  TRAIN: ("MPSC_train",)
  TEST: ("MPSC_test",)
MODEL:
  TRANSFORMER:
    USE_POLYGON: True
    NUM_CTRL_POINTS: 8
    LOSS:
      POINT_TEXT_WEIGHT: 4.0
TEST:
  USE_LEXICON: True
  LEXICON_TYPE: 3
  WEIGHTED_EDIT_DIST: True
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 1000, 1200, 1400)
  MAX_SIZE_TRAIN: 2555
  MIN_SIZE_TEST: 200
  MAX_SIZE_TEST: 639
